import type { Course, PracticeSentence } from '@/app/lib/definitions';

export const courses: Course[] = [
  {
    id: 'shadowing-101',
    title: 'Shadowing Man',
    description: '基礎影子跟讀課程，從簡單句子開始。(男聲)',
    actionLabel: '開始練習',
    practicePath: '/dashboard/course/practice',
  },
  {
    id: 'daily-practice',
    title: 'Shadowing Women',
    description: '基礎影子跟讀課程，從簡單句子開始。(女聲)',
    actionLabel: '開始練習',
    practicePath: '/dashboard/course/practice',
  },
];

export const practiceSentences: Record<string, PracticeSentence[]> = {
  'shadowing-101': [
    {
      id: 1,
      text: 'Author of the danger trail, Philip Steels, etc.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0001.wav',
    },
    {
      id: 2,
      text: 'Not at this particular case, Tom, apologized Whittemore.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0002.wav',
    },
    {
      id: 3,
      text: 'For the twentieth time that evening the two men shook hands.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0003.wav',
    },
    {
      id: 4,
      text: "Lord, but I'm glad to see you again, Phil.",
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0004.wav',
    },
    {
      id: 5,
      text: 'Will we ever forget it.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0005.wav',
    },
    {
      id: 6,
      text: "God bless 'em, I hope I'll go on seeing them forever.",
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0006.wav',
    },
    {
      id: 7,
      text: 'And you always want to see it in the superlative degree.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0007.wav',
    },
    {
      id: 8,
      text: 'Gad, your letter came just in time.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0008.wav',
    },
    {
      id: 9,
      text: 'He turned sharply, and faced Gregson across the table.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0009.wav',
    },
    {
      id: 10,
      text: "I'm playing a single hand in what looks like a losing game.",
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0010.wav',
    },
    {
      id: 11,
      text: 'If I ever needed a fighter in my life I need one now.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0011.wav',
    },
    {
      id: 12,
      text: 'Gregson shoved back his chair and rose to his feet.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0012.wav',
    },
    {
      id: 13,
      text: 'He was a head shorter than his companion, of almost delicate physique.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0013.wav',
    },
    {
      id: 14,
      text: "Now you're coming down to business, Phil, he exclaimed.",
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0014.wav',
    },
    {
      id: 15,
      text: "It's the aurora borealis.",
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0015.wav',
    },
    {
      id: 16,
      text: "There's Fort Churchill, a rifle-shot beyond the ridge, asleep.",
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0016.wav',
    },
    {
      id: 17,
      text: 'From that moment his friendship for Belize turns to hatred and jealousy.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0017.wav',
    },
    {
      id: 18,
      text: 'There was a change now.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0018.wav',
    },
    {
      id: 19,
      text: 'I followed the line of the proposed railroad, looking for chances.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0019.wav',
    },
    {
      id: 20,
      text: 'Clubs and balls and cities grew to be only memories.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0020.wav',
    },
    {
      id: 21,
      text: 'It fairly clubbed me into recognizing it.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0021.wav',
    },
    {
      id: 22,
      text: 'Hardly were our plans made public before we were met by powerful opposition.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0022.wav',
    },
    {
      id: 23,
      text: 'A combination of Canadian capital quickly organized and petitioned for the same privileges.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0023.wav',
    },
    {
      id: 24,
      text: 'It was my reports from the north which chiefly induced people to buy.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0024.wav',
    },
    {
      id: 25,
      text: 'I was about to do this when cooler judgment prevailed.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0025.wav',
    },
    {
      id: 26,
      text: 'It occurred to me that there would have to be an accounting.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0026.wav',
    },
    {
      id: 27,
      text: 'To my surprise he began to show actual enthusiasm in my favor.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0027.wav',
    },
    {
      id: 28,
      text: 'Robbery, bribery, fraud, ',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0028.wav',
    },
    {
      id: 29,
      text: 'Their forces were already moving into the north country.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0029.wav',
    },
    {
      id: 30,
      text: 'I had faith in them.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0030.wav',
    },
    {
      id: 31,
      text: 'They were three hundred yards apart.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0031.wav',
    },
    {
      id: 32,
      text: 'Since then some mysterious force has been fighting us at every step.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0032.wav',
    },
    {
      id: 33,
      text: 'He unfolded a long typewritten letter, and handed it to Gregson.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0033.wav',
    },
    {
      id: 34,
      text: "Men of Selden's stamp don't stop at women and children.",
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0034.wav',
    },
    {
      id: 35,
      text: 'He stopped, and Philip nodded at the horrified question in his eyes.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0035.wav',
    },
    {
      id: 36,
      text: 'She turned in at the hotel.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0036.wav',
    },
    {
      id: 37,
      text: 'I was the only one who remained sitting.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0037.wav',
    },
    {
      id: 38,
      text: "We'll have to watch our chances.",
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0038.wav',
    },
    {
      id: 39,
      text: 'The ship should be in within a week or ten days.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0039.wav',
    },
    {
      id: 40,
      text: 'I suppose you wonder why she is coming up here.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0040.wav',
    },
  ],
  'daily-practice': [
    {
      id: 1,
      text: 'Author of the danger trail, Philip Steels, etc.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0001.wav',
    },
    {
      id: 2,
      text: 'Not at this particular case, Tom, apologized Whittemore.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0002.wav',
    },
    {
      id: 3,
      text: 'For the twentieth time that evening the two men shook hands.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0003.wav',
    },
    {
      id: 4,
      text: "Lord, but I'm glad to see you again, Phil.",
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0004.wav',
    },
    {
      id: 5,
      text: 'Will we ever forget it.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0005.wav',
    },
    {
      id: 6,
      text: "God bless 'em, I hope I'll go on seeing them forever.",
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0006.wav',
    },
    {
      id: 7,
      text: 'And you always want to see it in the superlative degree.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0007.wav',
    },
    {
      id: 8,
      text: 'Gad, your letter came just in time.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0008.wav',
    },
    {
      id: 9,
      text: 'He turned sharply, and faced Gregson across the table.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0009.wav',
    },
    {
      id: 10,
      text: "I'm playing a single hand in what looks like a losing game.",
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0010.wav',
    },
    {
      id: 11,
      text: 'If I ever needed a fighter in my life I need one now.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0011.wav',
    },
    {
      id: 12,
      text: 'Gregson shoved back his chair and rose to his feet.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0012.wav',
    },
    {
      id: 13,
      text: 'He was a head shorter than his companion, of almost delicate physique.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0013.wav',
    },
    {
      id: 14,
      text: "Now you're coming down to business, Phil, he exclaimed.",
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0014.wav',
    },
    {
      id: 15,
      text: "It's the aurora borealis.",
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0015.wav',
    },
    {
      id: 16,
      text: "There's Fort Churchill, a rifle-shot beyond the ridge, asleep.",
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0016.wav',
    },
    {
      id: 17,
      text: 'From that moment his friendship for Belize turns to hatred and jealousy.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0017.wav',
    },
    {
      id: 18,
      text: 'There was a change now.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0018.wav',
    },
    {
      id: 19,
      text: 'I followed the line of the proposed railroad, looking for chances.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0019.wav',
    },
    {
      id: 20,
      text: 'Clubs and balls and cities grew to be only memories.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0020.wav',
    },
    {
      id: 21,
      text: 'It fairly clubbed me into recognizing it.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0021.wav',
    },
    {
      id: 22,
      text: 'Hardly were our plans made public before we were met by powerful opposition.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0022.wav',
    },
    {
      id: 23,
      text: 'A combination of Canadian capital quickly organized and petitioned for the same privileges.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0023.wav',
    },
    {
      id: 24,
      text: 'It was my reports from the north which chiefly induced people to buy.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0024.wav',
    },
    {
      id: 25,
      text: 'I was about to do this when cooler judgment prevailed.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0025.wav',
    },
    {
      id: 26,
      text: 'It occurred to me that there would have to be an accounting.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0026.wav',
    },
    {
      id: 27,
      text: 'To my surprise he began to show actual enthusiasm in my favor.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0027.wav',
    },
    {
      id: 28,
      text: 'Robbery, bribery, fraud, ',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0028.wav',
    },
    {
      id: 29,
      text: 'Their forces were already moving into the north country.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0029.wav',
    },
    {
      id: 30,
      text: 'I had faith in them.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0030.wav',
    },
    {
      id: 31,
      text: 'They were three hundred yards apart.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0031.wav',
    },
    {
      id: 32,
      text: 'Since then some mysterious force has been fighting us at every step.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0032.wav',
    },
    {
      id: 33,
      text: 'He unfolded a long typewritten letter, and handed it to Gregson.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0033.wav',
    },
    {
      id: 34,
      text: "Men of Selden's stamp don't stop at women and children.",
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0034.wav',
    },
    {
      id: 35,
      text: 'He stopped, and Philip nodded at the horrified question in his eyes.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0035.wav',
    },
    {
      id: 36,
      text: 'She turned in at the hotel.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0036.wav',
    },
    {
      id: 37,
      text: 'I was the only one who remained sitting.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0037.wav',
    },
    {
      id: 38,
      text: "We'll have to watch our chances.",
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0038.wav',
    },
    {
      id: 39,
      text: 'The ship should be in within a week or ten days.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0039.wav',
    },
    {
      id: 40,
      text: 'I suppose you wonder why she is coming up here.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0040.wav',
    },
  ],
};

export const defaultPracticeCourseId = 'shadowing-101';