import type { Course, PracticeSentence } from '@/app/lib/definitions';

export const courses: Course[] = [
  {
    id: 'shadowing-101',
    title: 'Shadowing Man',
    description: '基礎影子跟讀課程，從簡單句子開始。(男聲)',
    actionLabel: '開始練習',
    practicePath: '/dashboard/course/practice?courseId=shadowing-101',
  },
  {
    id: 'daily-practice',
    title: 'Shadowing Women',
    description: '基礎影子跟讀課程，從簡單句子開始。(女聲)',
    actionLabel: '開始練習',
    practicePath: '/dashboard/course/practice?courseId=daily-practice',
  },
  {
    id: 'truku-indigenous',
    title: '太魯閣族語',
    description: '太魯閣族語跟讀課程，學習原住民族語言。(5句)',
    actionLabel: '開始練習',
    practicePath: '/dashboard/course/practice?courseId=truku-indigenous',
  },
  {
    id: 'taiwanese',
    title: '台語跟讀',
    description: '台語跟讀課程，學習台灣閩南語。(5句)',
    actionLabel: '開始練習',
    practicePath: '/dashboard/course/practice?courseId=taiwanese',
  },
  {
    id: 'hakka',
    title: '客語錄音',
    description: '客家語跟讀課程，學習客家話。(4句)',
    actionLabel: '開始練習',
    practicePath: '/dashboard/course/practice?courseId=hakka',
  },
  {
    id: 'bunun-indigenous',
    title: '布農族語',
    description: '布農族語跟讀課程，學習原住民族語言。(5句)',
    actionLabel: '開始練習',
    practicePath: '/dashboard/course/practice?courseId=bunun-indigenous',
  },
];

export const practiceSentences: Record<string, PracticeSentence[]> = {
  'shadowing-101': [
    {
      id: 1,
      text: 'Author of the danger trail, Philip Steels, etc.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0001.wav',
    },
    {
      id: 2,
      text: 'Not at this particular case, Tom, apologized Whittemore.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0002.wav',
    },
    {
      id: 3,
      text: 'For the twentieth time that evening the two men shook hands.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0003.wav',
    },
    {
      id: 4,
      text: "Lord, but I'm glad to see you again, Phil.",
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0004.wav',
    },
    {
      id: 5,
      text: 'Will we ever forget it.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0005.wav',
    },
    {
      id: 6,
      text: "God bless 'em, I hope I'll go on seeing them forever.",
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0006.wav',
    },
    {
      id: 7,
      text: 'And you always want to see it in the superlative degree.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0007.wav',
    },
    {
      id: 8,
      text: 'Gad, your letter came just in time.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0008.wav',
    },
    {
      id: 9,
      text: 'He turned sharply, and faced Gregson across the table.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0009.wav',
    },
    {
      id: 10,
      text: "I'm playing a single hand in what looks like a losing game.",
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0010.wav',
    },
    {
      id: 11,
      text: 'If I ever needed a fighter in my life I need one now.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0011.wav',
    },
    {
      id: 12,
      text: 'Gregson shoved back his chair and rose to his feet.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0012.wav',
    },
    {
      id: 13,
      text: 'He was a head shorter than his companion, of almost delicate physique.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0013.wav',
    },
    {
      id: 14,
      text: "Now you're coming down to business, Phil, he exclaimed.",
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0014.wav',
    },
    {
      id: 15,
      text: "It's the aurora borealis.",
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0015.wav',
    },
    {
      id: 16,
      text: "There's Fort Churchill, a rifle-shot beyond the ridge, asleep.",
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0016.wav',
    },
    {
      id: 17,
      text: 'From that moment his friendship for Belize turns to hatred and jealousy.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0017.wav',
    },
    {
      id: 18,
      text: 'There was a change now.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0018.wav',
    },
    {
      id: 19,
      text: 'I followed the line of the proposed railroad, looking for chances.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0019.wav',
    },
    {
      id: 20,
      text: 'Clubs and balls and cities grew to be only memories.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0020.wav',
    },
    {
      id: 21,
      text: 'It fairly clubbed me into recognizing it.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0021.wav',
    },
    {
      id: 22,
      text: 'Hardly were our plans made public before we were met by powerful opposition.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0022.wav',
    },
    {
      id: 23,
      text: 'A combination of Canadian capital quickly organized and petitioned for the same privileges.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0023.wav',
    },
    {
      id: 24,
      text: 'It was my reports from the north which chiefly induced people to buy.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0024.wav',
    },
    {
      id: 25,
      text: 'I was about to do this when cooler judgment prevailed.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0025.wav',
    },
    {
      id: 26,
      text: 'It occurred to me that there would have to be an accounting.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0026.wav',
    },
    {
      id: 27,
      text: 'To my surprise he began to show actual enthusiasm in my favor.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0027.wav',
    },
    {
      id: 28,
      text: 'Robbery, bribery, fraud, ',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0028.wav',
    },
    {
      id: 29,
      text: 'Their forces were already moving into the north country.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0029.wav',
    },
    {
      id: 30,
      text: 'I had faith in them.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0030.wav',
    },
    {
      id: 31,
      text: 'They were three hundred yards apart.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0031.wav',
    },
    {
      id: 32,
      text: 'Since then some mysterious force has been fighting us at every step.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0032.wav',
    },
    {
      id: 33,
      text: 'He unfolded a long typewritten letter, and handed it to Gregson.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0033.wav',
    },
    {
      id: 34,
      text: "Men of Selden's stamp don't stop at women and children.",
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0034.wav',
    },
    {
      id: 35,
      text: 'He stopped, and Philip nodded at the horrified question in his eyes.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0035.wav',
    },
    {
      id: 36,
      text: 'She turned in at the hotel.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0036.wav',
    },
    {
      id: 37,
      text: 'I was the only one who remained sitting.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0037.wav',
    },
    {
      id: 38,
      text: "We'll have to watch our chances.",
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0038.wav',
    },
    {
      id: 39,
      text: 'The ship should be in within a week or ten days.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0039.wav',
    },
    {
      id: 40,
      text: 'I suppose you wonder why she is coming up here.',
      translation: '男: ',
      audioSrc: '/audio/cmu_us_bdl_arctic/arctic_a0040.wav',
    },
  ],
  'daily-practice': [
    {
      id: 1,
      text: 'Author of the danger trail, Philip Steels, etc.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0001.wav',
    },
    {
      id: 2,
      text: 'Not at this particular case, Tom, apologized Whittemore.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0002.wav',
    },
    {
      id: 3,
      text: 'For the twentieth time that evening the two men shook hands.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0003.wav',
    },
    {
      id: 4,
      text: "Lord, but I'm glad to see you again, Phil.",
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0004.wav',
    },
    {
      id: 5,
      text: 'Will we ever forget it.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0005.wav',
    },
    {
      id: 6,
      text: "God bless 'em, I hope I'll go on seeing them forever.",
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0006.wav',
    },
    {
      id: 7,
      text: 'And you always want to see it in the superlative degree.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0007.wav',
    },
    {
      id: 8,
      text: 'Gad, your letter came just in time.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0008.wav',
    },
    {
      id: 9,
      text: 'He turned sharply, and faced Gregson across the table.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0009.wav',
    },
    {
      id: 10,
      text: "I'm playing a single hand in what looks like a losing game.",
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0010.wav',
    },
    {
      id: 11,
      text: 'If I ever needed a fighter in my life I need one now.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0011.wav',
    },
    {
      id: 12,
      text: 'Gregson shoved back his chair and rose to his feet.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0012.wav',
    },
    {
      id: 13,
      text: 'He was a head shorter than his companion, of almost delicate physique.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0013.wav',
    },
    {
      id: 14,
      text: "Now you're coming down to business, Phil, he exclaimed.",
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0014.wav',
    },
    {
      id: 15,
      text: "It's the aurora borealis.",
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0015.wav',
    },
    {
      id: 16,
      text: "There's Fort Churchill, a rifle-shot beyond the ridge, asleep.",
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0016.wav',
    },
    {
      id: 17,
      text: 'From that moment his friendship for Belize turns to hatred and jealousy.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0017.wav',
    },
    {
      id: 18,
      text: 'There was a change now.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0018.wav',
    },
    {
      id: 19,
      text: 'I followed the line of the proposed railroad, looking for chances.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0019.wav',
    },
    {
      id: 20,
      text: 'Clubs and balls and cities grew to be only memories.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0020.wav',
    },
    {
      id: 21,
      text: 'It fairly clubbed me into recognizing it.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0021.wav',
    },
    {
      id: 22,
      text: 'Hardly were our plans made public before we were met by powerful opposition.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0022.wav',
    },
    {
      id: 23,
      text: 'A combination of Canadian capital quickly organized and petitioned for the same privileges.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0023.wav',
    },
    {
      id: 24,
      text: 'It was my reports from the north which chiefly induced people to buy.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0024.wav',
    },
    {
      id: 25,
      text: 'I was about to do this when cooler judgment prevailed.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0025.wav',
    },
    {
      id: 26,
      text: 'It occurred to me that there would have to be an accounting.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0026.wav',
    },
    {
      id: 27,
      text: 'To my surprise he began to show actual enthusiasm in my favor.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0027.wav',
    },
    {
      id: 28,
      text: 'Robbery, bribery, fraud, ',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0028.wav',
    },
    {
      id: 29,
      text: 'Their forces were already moving into the north country.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0029.wav',
    },
    {
      id: 30,
      text: 'I had faith in them.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0030.wav',
    },
    {
      id: 31,
      text: 'They were three hundred yards apart.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0031.wav',
    },
    {
      id: 32,
      text: 'Since then some mysterious force has been fighting us at every step.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0032.wav',
    },
    {
      id: 33,
      text: 'He unfolded a long typewritten letter, and handed it to Gregson.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0033.wav',
    },
    {
      id: 34,
      text: "Men of Selden's stamp don't stop at women and children.",
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0034.wav',
    },
    {
      id: 35,
      text: 'He stopped, and Philip nodded at the horrified question in his eyes.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0035.wav',
    },
    {
      id: 36,
      text: 'She turned in at the hotel.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0036.wav',
    },
    {
      id: 37,
      text: 'I was the only one who remained sitting.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0037.wav',
    },
    {
      id: 38,
      text: "We'll have to watch our chances.",
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0038.wav',
    },
    {
      id: 39,
      text: 'The ship should be in within a week or ten days.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0039.wav',
    },
    {
      id: 40,
      text: 'I suppose you wonder why she is coming up here.',
      translation: '女: ',
      audioSrc: '/audio/cmu_us_clb_arctic/arctic_a0040.wav',
    },
  ],
  'truku-indigenous': [
    {
      id: 1,
      text: 'Hiya o lupung mu.',
      translation: '他是我的朋友。',
      audioSrc: '/audio/truku_indigenous/tst1.mp3',
    },
    {
      id: 2,
      text: 'Niqan cih blbul ka hini.',
      translation: '這裡有一些香蕉。',
      audioSrc: '/audio/truku_indigenous/tst2.mp3',
    },
    {
      id: 3,
      text: 'Qmnuyux paru bi quyux.',
      translation: '下過一場大雨。',
      audioSrc: '/audio/truku_indigenous/tst3.mp3',
    },
    {
      id: 4,
      text: 'Malu ka karat sayang da.',
      translation: '今天天氣好了。',
      audioSrc: '/audio/truku_indigenous/tst4.mp3',
    },
    {
      id: 5,
      text: 'Knuwan ka pneingan su?',
      translation: '你的生日是什麼時候？',
      audioSrc: '/audio/truku_indigenous/tst5.mp3',
    },
  ],
  'taiwanese': [
    {
      id: 1,
      text: '我不知道發生什麼事情?',
      translation: '',
      audioSrc: '/audio/taiwanese/taiwan_ref_01.mp3',
    },
    {
      id: 2,
      text: '我早就知道他有問題',
      translation: '',
      audioSrc: '/audio/taiwanese/taiwan_ref_02.mp3',
    },
    {
      id: 3,
      text: '這件事情我們有需要商量一下',
      translation: '',
      audioSrc: '/audio/taiwanese/taiwan_ref_03.mp3',
    },
    {
      id: 4,
      text: '你出門在外，自己千萬要小心',
      translation: '',
      audioSrc: '/audio/taiwanese/taiwan_ref_04.mp3',
    },
    {
      id: 5,
      text: '下雨天的時候，這條路就變得很難走',
      translation: '',
      audioSrc: '/audio/taiwanese/taiwan_ref_05.mp3',
    },
  ],
  'hakka': [
    {
      id: 1,
      text: '你會肚屎枵無？',
      translation: '你餓嗎？',
      audioSrc: '/audio/hakka/hakka_gt_1.mp3',
    },
    {
      id: 2,
      text: '請問高鐵車頭仰般行？',
      translation: '請問高鐵車站怎麼走？',
      audioSrc: '/audio/hakka/hakka_gt_2.mp3',
    },
    {
      id: 3,
      text: '來去點心店食點心！',
      translation: '到小吃店去吃點心！',
      audioSrc: '/audio/hakka/hakka_gt_3.mp3',
    },
    {
      id: 4,
      text: '今晡日放尞，毋使去學校。',
      translation: '今天放假，不必上學。',
      audioSrc: '/audio/hakka/hakka_gt_4.mp3',
    },
  ],
  'bunun-indigenous': [
    {
      id: 1,
      text: 'Mihumisang, muhnang maisin pasadu.',
      translation: '再見，下次再相見。',
      audioSrc: '/audio/bunun_indigenous/1.mp3',
    },
    {
      id: 2,
      text: 'Mandia saikin mas maibabu mais maun haising.',
      translation: '我吃飯時配豬肉。',
      audioSrc: '/audio/bunun_indigenous/2.mp3',
    },
    {
      id: 3,
      text: 'Iskunghuav kuzkuza-unan ii, aupa namaunin haising.',
      translation: '停下這個工作吧，因為已經要吃飯了。',
      audioSrc: '/audio/bunun_indigenous/3.mp3',
    },
    {
      id: 4,
      text: 'Nakudiip a inaak tama hanup.',
      translation: '我爸爸要去打獵。',
      audioSrc: '/audio/bunun_indigenous/4.mp3',
    },
    {
      id: 5,
      text: 'Niin laupaku uvavaaz mazima maun pintcingmut.',
      translation: '現在的小孩不喜歡吃早餐了。',
      audioSrc: '/audio/bunun_indigenous/5.mp3',
    },
  ],
};

export const defaultPracticeCourseId = 'shadowing-101';
